export const stock = [
  {
    id: 1,
    nombre: "Red Dragon Pandora 2",
    precio: "14.000",
    desc: "320GB Slim",
    img: "/img/categorias/Auriculares/auri_1.jpg",
    stock: 50,
    categoria: "auriculares",
  },
  {
    id: 2,
    nombre: "Cat Ear VZV-23M",
    precio: 15.999,
    desc: "320GB Slim",
    img: "/img/categorias/Auriculares/auri_2.jpg",
    stock: 10,
    categoria: "auriculares",
  },
  {
    id: 3,
    nombre: "Auriculares Gamer SteelSeries Arctis Pro 5",
    precio: 45.389,
    desc: "320GB Slim",
    img: "/img/categorias/Auriculares/auri_3.webp",
    stock: 10,
    categoria: "auriculares",
  },
  {
    id: 4,
    nombre: "Apple AirPods Blanco",
    precio: 26.499,
    desc: "320GB Slim",
    img: "/img/categorias/Auriculares/auri_4.jpg",
    stock: 10,
    categoria: "auriculares",
  },
  {
    id: 5,
    nombre: "Auriculares In-Ear Sony WF-1000XM4",
    precio: 18.999,
    desc: "320GB Slim",
    img: "/img/categorias/Auriculares/auri_5.jpg",
    stock: 10,
    categoria: "auriculares",
  },
  {
    id: 6,
    nombre: "Auriculares In-Ear Samsung Galaxy  Buds Pro negro",
    precio: 24.999,
    desc: "320GB Slim",
    img: "img/categorias/Auriculares/auri_6.jpg",
    stock: 10,
    categoria: "auriculares",
  },
  {
    id: 7,
    nombre: "Mini Drone DJI Mavic Mini 2 DRDJI018",
    precio: "145.000",
    desc: "320GB Slim",
    img: "/img/categorias/Drone/drone_1.png",
    stock: 10,
    categoria: "drone",
  },
  {
    id: 8,
    nombre: "Drone Daming DM107S",
    precio: "16.000",
    desc: "320GB Slim",
    img: "/img/categorias/Drone/drone_2.webp",
    stock: 10,
    categoria: "drone",
  },
  {
    id: 9,
    nombre: "Drone DJI Mavic 3 Pro Premium 4K",
    precio: "569.000",
    desc: "320GB Slim",
    img: "/img/categorias/Drone/drone_3.jpg",
    stock: 10,
    categoria: "drone",
  },
  {
    id: 10,
    nombre: "Drone Parrot Thermal 4k",
    precio: "546.000",
    desc: "320GB Slim",
    img: "/img/categorias/Drone/drone_4.webp",
    stock: 10,
    categoria: "drone",
  },
  {
    id: 11,
    nombre: "Drone Phantom 4 Pro Obsidian",
    precio: "539.000",
    desc: "320GB Slim",
    img: "/img/categorias/Drone/drone_5.jpg",
    stock: 10,
    categoria: "drone",
  },
  {
    id: 12,
    nombre: "Notebook Asus ZenBook UX581LV",
    precio: "2.367.300",
    desc: "320GB Slim",
    img: "/img/categorias/Notebook/nbk_1.webp",
    stock: 10,
    categoria: "notebook",
  },
  {
    id: 13,
    nombre: "Asus Rog Strix G533qs",
    precio: "1.066.000",
    desc: "320GB Slim",
    img: "/img/categorias/Notebook/nbk_2.jpg",
    stock: 10,
    categoria: "notebook",
  },
  {
    id: 14,
    nombre: "Macbook Pro 14' M1 Pro",
    precio: "952.000",
    desc: "320GB Slim",
    img: "/img/categorias/Notebook/nbk_3.jpg",
    stock: 10,
    categoria: "notebook",
  },
  {
    id: 15,
    nombre: "Lenovo Legion 5 17",
    precio: "450.999",
    desc: "320GB Slim",
    img: "/img/categorias/Notebook/nbk_4.jpg",
    stock: 10,
    categoria: "notebook",
  },
  {
    id: 16,
    nombre: "Notebook Dell AlienWare M15",
    precio: "389.000",
    desc: "320GB Slim",
    img: "/img/categorias/Notebook/nbk_5.jpg",
    stock: 10,
    categoria: "notebook",
  },
  {
    id: 17,
    nombre: "Huawei P50 Pro",
    precio: "400.000",
    desc: "320GB Slim",
    img: "/img/categorias/Celulares/celu_1.webp",
    stock: 10,
    categoria: "celulares",
  },
  {
    id: 18,
    nombre: "Apple iPhone 13 Pro Max",
    precio: "380.000",
    desc: "320GB Slim",
    img: "/img/categorias/Celulares/celu_2.jpg",
    stock: 10,
    categoriay: "celulares",
  },
  {
    id: 19,
    nombre: "Samsung Galaxy S21",
    precio: "124.000",
    desc: "320GB Slim",
    img: "/img/categorias/Celulares/celu_3.webp",
    stock: 10,
    categoria: "celulares",
  },
  {
    id: 20,
    nombre: "Samsung Galaxy S22 Ultra",
    precio: "229.000",
    desc: "320GB Slim",
    img: "/img/categorias/Celulares/celu_4.jpg",
    stock: 10,
    categoria: "celulares",
  },
  {
    id: 21,
    nombre: "Xiaomi Pocophone Poco X3",
    precio: "82.300",
    desc: "320GB Slim",
    img: "/img/categorias/Celulares/celu_5.png",
    stock: 10,
    categoria: "celulares",
  },
  {
    id: 22,
    nombre: "Nintendo Switch Standard",
    precio: "79.999",
    desc: "320GB Slim",
    img: "/img/categorias/Consolas/consola_1.png",
    stock: 10,
    categoria: "consolas",
  },
  {
    id: 23,
    nombre: "Sony PlayStation 4 Slim",
    precio: "113.800",
    desc: "320GB Slim",
    img: "/img/categorias/Consolas/consola_2.jpg",
    stock: 10,
    categoria: "consolas",
  },
  {
    id: 24,
    nombre: "Sony PlayStation 5 Digital Edition",
    precio: "245.000",
    desc: "320GB Slim",
    img: "/img/categorias/Consolas/consola_3.jpg",
    stock: 10,
    categoria: "consolas",
  },
];
